algoritmo "contar de 0 a 10"
// Função :
// Autor :
// Data : 27/08/2021
// Seção de Declarações 
var
    I, contador, valor: inteiro
inicio
    contador <- 0
    Escreval ("Quer contar ate quanto?" )
    Leia(valor)
    Escreval ("Qual o valor do intervalo?" )
    Leia(I)
    enquanto (contador <= valor ) faca
       escreval(contador)
       contador <- contador + I
    FimEnquanto
fimalgoritmo
