algoritmo "habilitação"
// Função :
// Autor :
// Data : 25/08/2021
// Seção de Declarações 
var
     AA, N, I: real
inicio
     Escreval("Digite o ano atual: ")
      leia(AA)
     Escreval("Digite sua data de nascimento: ")
      Leia(N)
     I <- (AA-N)
           Se (I>=18) entao
       Escreval("Voce esta apto a dirigir")
      senao
       Escreval("Voce nao esta apto a dirigir")
      FimSe
     
     
fimalgoritmo
